/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author Aluno
 */
public class TelaInicio extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicio
     */
    public TelaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btgFilmes = new javax.swing.ButtonGroup();
        btgSeries = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rdbCadastrarFilme = new javax.swing.JRadioButton();
        rdbDeletarFilme = new javax.swing.JRadioButton();
        rdbAtualizarNota = new javax.swing.JRadioButton();
        rdbConsultarNomeEGenero = new javax.swing.JRadioButton();
        rdbConsultarTudo = new javax.swing.JRadioButton();
        rdbAumentarNota = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(400, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Gerenciador");

        btgFilmes.add(rdbCadastrarFilme);
        rdbCadastrarFilme.setText("Cadastrar Novo Filme");
        rdbCadastrarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCadastrarFilmeActionPerformed(evt);
            }
        });

        btgFilmes.add(rdbDeletarFilme);
        rdbDeletarFilme.setText("Deletar Filme [ID]");
        rdbDeletarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbDeletarFilmeActionPerformed(evt);
            }
        });

        btgFilmes.add(rdbAtualizarNota);
        rdbAtualizarNota.setText("Atualizar Nota [ID]");
        rdbAtualizarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbAtualizarNotaActionPerformed(evt);
            }
        });

        btgFilmes.add(rdbConsultarNomeEGenero);
        rdbConsultarNomeEGenero.setText("Consultar Nome e Genero [ID]");
        rdbConsultarNomeEGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbConsultarNomeEGeneroActionPerformed(evt);
            }
        });

        btgFilmes.add(rdbConsultarTudo);
        rdbConsultarTudo.setText("Consultar Filme [ID]");
        rdbConsultarTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbConsultarTudoActionPerformed(evt);
            }
        });

        btgFilmes.add(rdbAumentarNota);
        rdbAumentarNota.setText("Aumentar Nota Em 1 ponto [ID]");
        rdbAumentarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbAumentarNotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbDeletarFilme)
                            .addComponent(rdbCadastrarFilme)
                            .addComponent(rdbAtualizarNota)
                            .addComponent(rdbConsultarNomeEGenero)
                            .addComponent(rdbConsultarTudo)
                            .addComponent(rdbAumentarNota))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbCadastrarFilme)
                .addGap(18, 18, 18)
                .addComponent(rdbDeletarFilme)
                .addGap(18, 18, 18)
                .addComponent(rdbAtualizarNota)
                .addGap(18, 18, 18)
                .addComponent(rdbConsultarNomeEGenero)
                .addGap(18, 18, 18)
                .addComponent(rdbConsultarTudo)
                .addGap(18, 18, 18)
                .addComponent(rdbAumentarNota)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void rdbAtualizarNotaActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        TelaAlterarNota tan = new TelaAlterarNota();
        tan.setVisible(true);
    }                                                

    private void rdbCadastrarFilmeActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        TelaCadastrarFilme tcf = new TelaCadastrarFilme();
        tcf.setVisible(true);
    }                                                 

    private void rdbDeletarFilmeActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        TelaDeletarFilme tdf = new TelaDeletarFilme();
        tdf.setVisible(true);
    }                                               

    private void rdbConsultarNomeEGeneroActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        // TODO add your handling code here:
        TelaConsultarNomeEGenero tcng = new TelaConsultarNomeEGenero();
        tcng.setVisible(true);
    }                                                       

    private void rdbConsultarTudoActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        TelaConsultarFilme tcf = new TelaConsultarFilme();
        tcf.setVisible(true);
    }                                                

    private void rdbAumentarNotaActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        TelaAumentarNota tan = new TelaAumentarNota();
        tan.setVisible(true);
    }                                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup btgFilmes;
    private javax.swing.ButtonGroup btgSeries;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdbAtualizarNota;
    private javax.swing.JRadioButton rdbAumentarNota;
    private javax.swing.JRadioButton rdbCadastrarFilme;
    private javax.swing.JRadioButton rdbConsultarNomeEGenero;
    private javax.swing.JRadioButton rdbConsultarTudo;
    private javax.swing.JRadioButton rdbDeletarFilme;
    // End of variables declaration                   
}
