/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telaEmail;

import emailutil.EmailUtil;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.mail.internet.AddressException;


/**
 *
 * @author Aluno
 */
public class TelaEmail extends javax.swing.JFrame {
     private String remetente, para, assunto, mensagem;
     
     
     private static void enviarEmail(String assunto, String de, String para, String mensagem) throws MessagingException, AddressException, UnsupportedEncodingException {
        EmailUtil email = new EmailUtil();
        email.enviarEmail(assunto, de, para, mensagem);
    }
     
     
    /**
     * Creates new form TelaEmail
     */
    public TelaEmail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn01 = new javax.swing.JPanel();
        lblNovoEmail = new javax.swing.JLabel();
        lblDe = new javax.swing.JLabel();
        lblPara = new javax.swing.JLabel();
        txtDe = new javax.swing.JTextField();
        txtPara = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMensagem = new javax.swing.JTextArea();
        btnEnviar = new javax.swing.JButton();
        btnResetar = new javax.swing.JButton();
        txtAssunto = new javax.swing.JTextField();
        lblPara1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNovoEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNovoEmail.setText("NOVO EMAIL");

        lblDe.setText("De:");

        lblPara.setText("Para: ");

        txtPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParaActionPerformed(evt);
            }
        });

        txtMensagem.setColumns(20);
        txtMensagem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtMensagem.setRows(5);
        txtMensagem.setToolTipText("mensagem....");
        jScrollPane2.setViewportView(txtMensagem);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnResetar.setText("Resetar");
        btnResetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetarActionPerformed(evt);
            }
        });

        txtAssunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAssuntoActionPerformed(evt);
            }
        });

        lblPara1.setText("Assunto: ");

        javax.swing.GroupLayout pn01Layout = new javax.swing.GroupLayout(pn01);
        pn01.setLayout(pn01Layout);
        pn01Layout.setHorizontalGroup(
            pn01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn01Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pn01Layout.createSequentialGroup()
                            .addComponent(lblNovoEmail)
                            .addGap(135, 135, 135)
                            .addComponent(btnResetar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnEnviar))
                        .addGroup(pn01Layout.createSequentialGroup()
                            .addGroup(pn01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPara1)
                                .addComponent(lblPara)
                                .addComponent(lblDe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pn01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDe)
                                .addComponent(txtPara)
                                .addComponent(txtAssunto)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pn01Layout.setVerticalGroup(
            pn01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn01Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNovoEmail)
                    .addComponent(btnEnviar)
                    .addComponent(btnResetar))
                .addGap(18, 18, 18)
                .addGroup(pn01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDe)
                    .addComponent(txtDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPara)
                    .addComponent(txtPara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPara1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParaActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        remetente = txtDe.getText();
        para = txtPara.getText();
        assunto = txtAssunto.getText();
        mensagem = txtMensagem.getText();
        
         try {
             enviarEmail(assunto, remetente, para, mensagem);
         } catch (MessagingException | UnsupportedEncodingException ex) {
             Logger.getLogger(TelaEmail.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void txtAssuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAssuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAssuntoActionPerformed

    private void btnResetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetarActionPerformed
        // TODO add your handling code here:
        txtDe.setText(" ");
        txtPara.setText(" ");
        txtAssunto.setText(" ");
        txtMensagem.setText(" ");
    }//GEN-LAST:event_btnResetarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEmail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnResetar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDe;
    private javax.swing.JLabel lblNovoEmail;
    private javax.swing.JLabel lblPara;
    private javax.swing.JLabel lblPara1;
    private javax.swing.JPanel pn01;
    private javax.swing.JTextField txtAssunto;
    private javax.swing.JTextField txtDe;
    private javax.swing.JTextArea txtMensagem;
    private javax.swing.JTextField txtPara;
    // End of variables declaration//GEN-END:variables
}
