/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author Aluno
 */
public class TelaInicio extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicio
     */
    public TelaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCadAnimal = new javax.swing.JButton();
        btnCadRemedio = new javax.swing.JButton();
        btnConAnimal = new javax.swing.JButton();
        btnConRemedio = new javax.swing.JButton();
        btnDelAnimal = new javax.swing.JButton();
        btnDelRemedio = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));

        jLabel1.setText("MENU SELEÇÃO");

        btnCadAnimal.setText("Castrar Animal");
        btnCadAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadAnimalActionPerformed(evt);
            }
        });

        btnCadRemedio.setText("Cadastrar Remedio");
        btnCadRemedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadRemedioActionPerformed(evt);
            }
        });

        btnConAnimal.setText("Consultar Animal");
        btnConAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConAnimalActionPerformed(evt);
            }
        });

        btnConRemedio.setText("Consultar Remedio");
        btnConRemedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConRemedioActionPerformed(evt);
            }
        });

        btnDelAnimal.setText("Deletar Animal");
        btnDelAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelAnimalActionPerformed(evt);
            }
        });

        btnDelRemedio.setText("Deletar Remedio");
        btnDelRemedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelRemedioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadAnimal)
                    .addComponent(btnConAnimal)
                    .addComponent(btnDelAnimal))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelRemedio)
                    .addComponent(btnConRemedio)
                    .addComponent(btnCadRemedio))
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadAnimal)
                    .addComponent(btnCadRemedio))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConAnimal)
                    .addComponent(btnConRemedio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelAnimal)
                    .addComponent(btnDelRemedio)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadRemedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadRemedioActionPerformed
        // TODO add your handling code here:
        TelaCadastroRemedio cdR = new TelaCadastroRemedio();
        cdR.setVisible(true);
    }//GEN-LAST:event_btnCadRemedioActionPerformed

    private void btnConRemedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConRemedioActionPerformed
        // TODO add your handling code here:
        TelaConsultarRemedio tcr = new TelaConsultarRemedio();
        tcr.setVisible(true);
    }//GEN-LAST:event_btnConRemedioActionPerformed

    private void btnConAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConAnimalActionPerformed
        // TODO add your handling code here:
        TelaConsultaAnimal tca = new TelaConsultaAnimal();
        tca.setVisible(true);
        
    }//GEN-LAST:event_btnConAnimalActionPerformed

    private void btnCadAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadAnimalActionPerformed
        // TODO add your handling code here:
        TelaCadastroAnimal tcda = new TelaCadastroAnimal();
        tcda.setVisible(true);
    }//GEN-LAST:event_btnCadAnimalActionPerformed

    private void btnDelAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelAnimalActionPerformed
        // TODO add your handling code here:
        TelaDeletarAnimal tda = new TelaDeletarAnimal();
        tda.setVisible(true);
    }//GEN-LAST:event_btnDelAnimalActionPerformed

    private void btnDelRemedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelRemedioActionPerformed
        // TODO add your handling code here:
        TelaDeletarRemedio tdr = new TelaDeletarRemedio();
        tdr.setVisible(true);
    }//GEN-LAST:event_btnDelRemedioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadAnimal;
    private javax.swing.JButton btnCadRemedio;
    private javax.swing.JButton btnConAnimal;
    private javax.swing.JButton btnConRemedio;
    private javax.swing.JButton btnDelAnimal;
    private javax.swing.JButton btnDelRemedio;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
